[project]
name = "voice-bot-tester"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "audioop-lts>=0.2.2",
    "deepgram-sdk>=7.7.0",
    "fastapi>=0.141.1",
    "groq>=1.6.0",
    "httpx>=0.28.1",
    "ipynb>=0.5.1",
    "pydub>=0.25.1",
    "python-dotenv>=1.2.3",
    "pyyaml>=6.0.3",
    "twilio>=9.11.0",
    "uvicorn[standard]>=0.52.4",
    "websockets>=17.0.1",
]
